spring:
  application:
    name: users
  datasource:
    url: jdbc:h2:mem:users
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-ui
#      settings.web-allow-others: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

feign:
  client:
    randomuser:
      base-url: "https://randomuser.me/api/"

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    com.irn.users: DEBUG