spring:
  application:
    name: users
  datasource:
    url: jdbc:h2:mem:users
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    #TODO remove this on final version, unless want to load some sample data by default
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings.web-allow-others: false

feign:
  client:
    randomuser:
      base-url: "https://randomuser.me/api/"

